"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getBreakingChangeNotes = exports.getExcludeMessages = exports.getMinorUpdateCommitTypes = void 0;
const github_action_helper_1 = require("@technote-space/github-action-helper");
const getMinorUpdateCommitTypes = () => github_action_helper_1.Utils.getArrayInput('MINOR_UPDATE_TYPES');
exports.getMinorUpdateCommitTypes = getMinorUpdateCommitTypes;
const getExcludeMessages = () => github_action_helper_1.Utils.getArrayInput('EXCLUDE_MESSAGES');
exports.getExcludeMessages = getExcludeMessages;
const getBreakingChangeNotes = () => github_action_helper_1.Utils.getArrayInput('BREAKING_CHANGE_NOTES');
exports.getBreakingChangeNotes = getBreakingChangeNotes;
